language: node_js
node_js:
- stable
after_success: npm run coveralls
deploy:
  provider: npm
  email: yadickson@gmail.com
  api_key:
    secure: ZhGyUsCHKfELduz/gaCXAL304tFOoNcubS+hnFfmqdPkebamgdYos5rXf9dIWReJLl/ervBtZNKP5C4Q9uCtbYN9QsxUhhBvzJgK6ve+t88qXVjB4zz/UxXdyLPMuAjGFLxr4yz56QC/gBVL7Z53FXaWOVbplwJOm+R+1d5+blQg8Xai3r6wXk0fLDTvyhlIHn+zkLJh+Zi2k6GAezqAyf8PfcCqMkNwQCUJFh5o8EhBG+48yx/pkSkfYqpITggYEwBeBgbQ0jWO693iiK2T/YQbnL5Qolu6zOOIvL6p/3LjY35WEm6Nf9eZqp1KowSIPLe2+F3AShwmfIA2DcVnlPBRKWRmoMsQtBOkcNQvpIDUdZ35cVkLe673d9qjWrNVYCm8/1mUShI4Tl/BMkeaNGaefZs8Z7cVGkf19rEQCKstH5IMlLf5zKe1Uib+owBOjyTeorETgTjwwKwHlujifxzHTw7tGcHB2JTAsxOT4QW4DdPpm4TWdQklC3ztzc3bwg3WzKYvfs4nXdpyFBVAyZ/7Ckbm6BaJ6KviYCGxBCIZVfHuVv9D/4wI8M2msiLxM1MaqhkS+klpatG49S1I0N7jmU5PKf1BK+C1R1zE6WFH8HU0LbydJnMZTmXUJD5dsbgQi4fwjUleRncu31qW5+Y6muPlKcbcnB7F/2Fycf8=
  on:
    tags: true
